name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "New Features"
    labels: ["enhancement", "feature"]
  - title: "Bug Fixes"
    labels: ["bug", "fix"]
  - title: "Maintenance"
    labels: ["chore", "dependencies", "refactor"]
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
commit-template: "- $TITLE @$AUTHOR ($SHA)"
include-commits: true
include-pre-releases: false
version-resolver:
  major:
    labels: ["breaking change"]
  minor:
    labels: ["enhancement", "feature"]
  patch:
    labels: ["bug", "fix", "chore", "dependencies", "refactor"]
  default: patch
template: |
  ## Changes

  $CHANGES
